#!/usr/bin/env bash
#

source script/repos
command="$@"
printf "\nExecuting $command across all repos \n"

for repo in ${repos[@]};
do
    printf "\n******** $repo ********\n"
    cd $repo
    "$@"
    cd ../
done

printf "\n...executed $command \n"
