#!/usr/bin/env bash
#

cd core
npm link
jspm link -y

cd callback
npm link miruken-core
jspm install --link npm:miruken-core
npm link
jspm link -y

cd context
npm link miruken-core
npm link miruken-callback
jspm install --link npm:miruken-core
jspm install --link npm:miruken-callback


