#!/usr/bin/env bash
#

repos=(
    git@github.com:miruken-js/angular.git
    git@github.com:miruken-js/bootstrap.git
    git@github.com:miruken-js/callback.git
    git@github.com:miruken-js/context.git
    git@github.com:miruken-js/core.git
    git@github.com:miruken-js/demo-majorLeagueMiruken.git
    git@github.com:miruken-js/error.git
    git@github.com:miruken-js/ioc.git
    git@github.com:miruken-js/map.git
    git@github.com:miruken-js/mvc.git
    git@github.com:miruken-js/tools.git
    git@github.com:miruken-js/validate.git
)
