#!/usr/bin/env bash
#

repos=(
    #angular
    #bootstrap
    callback
    context
    core
    demo-majorLeagueMiruken
    error
    #framework
    ioc
    map
    mvc
    #registry
    #tools
    validate
)
